### ISSUE TITLE
画图功能怎么用呢？

### ISSUE THREAD

**Issue by 2132660698** [OpenLMLab/MOSS#10]
运行moss_cli_demo.py，得得到一个图片链接，不能访问。

![image](https://user-images.githubusercontent.com/94035926/233559464-640a4ec8-82ed-489b-a419-29f5f89ce45b.png)

**Comment by fushengwuyu** [comment]
你现在能画图了吗，我也没办法画图，不知道啥情况

**Comment by txsun1997** [comment]
@2132660698 @fushengwuyu 插件版MOSS的使用说明已经更新到README
