### ISSUE TITLE
运行量化版本安装triton失败

### ISSUE THREAD

**Issue by SitaraJin** [OpenLMLab/MOSS#117]
在安装triton时老是提示下面两个错误：
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
查了下，网上回答是triton包不支持windows...这个能不能注释一下...或者有没有哪位大神有编译好的whl包？目前只找到适用于python3.10的，这里又要求python3.8

**Comment by priest2018** [comment]
from .custom_autotune import *  是这行代码的问题。不清楚这个哪里来的，希望作者能看一下

**Comment by 937739823** [comment]
我试了 ubuntu18.4 triton2.1 也编译不过去，官方能否给个 量化版本的 docker 镜像啊，这个环境搭建废了好几天，也么成功。

**Comment by SitaraJin** [comment]
> 我试了 ubuntu18.4 triton2.1 也编译不过去，官方能否给个 量化版本的 docker 镜像啊，这个环境搭建废了好几天，也么成功。

确实，我换成ubuntu，到调用triton一直不行，装上了triton也显示autotune不可用，一直提示安装triton

**Comment by cnsky2016** [comment]
> > 我试了 ubuntu18.4 triton2.1 也编译不过去，官方能否给个 量化版本的 docker 镜像啊，这个环境搭建废了好几天，也么成功。
> 
> 确实，我换成ubuntu，到调用triton一直不行，装上了triton也显示autotune不可用，一直提示安装triton

我这边是把models目录里的custom_autotune.py文件放在~/.cache/huggingface/modules/transformers_modules/local/ 目录下解决

**Comment by UTimeStrange** [comment]
triton装了也一直显示triton not installed. Run `pip install triton` to load quantized version of MOSS.  NameError: name 'autotune' is not defined.

**Comment by ChangxingSu** [comment]
经过测试，发现多次重新卸载pip uninstall triton后重新安装triton即可运行。

**Comment by SitaraJin** [comment]
> 经过测试，发现多次重新卸载pip uninstall triton后重新安装triton即可运行。

指定安装triton2.0.0后成功，默认安装是带post1后缀版本的，替换之后就可以了。
