### ISSUE TITLE
请问是否准备把webui也开源了

### ISSUE THREAD

**Issue by milk-bottle-liyu** [OpenLMLab/MOSS#12]

**Comment by txsun1997** [comment]
Hi @milk-bottle-liyu @fzy0728 
MOSS前端：https://github.com/singularity-s0/openchat_frontend
MOSS后端：https://github.com/JingYiJun/MOSS_backend

**Comment by kanseaveg** [comment]
蹲到了~感谢感谢~

**Comment by milk-bottle-liyu** [comment]
膜拜膜拜~~
