### ISSUE TITLE
Plugin开关问题

### ISSUE THREAD

**Issue by camphora** [OpenLMLab/MOSS#137]
您好，正在本地调试moss-moon-sft-plugin 的相关效果，但是似乎模型并不能展示训练语料与宣城的支持plugin功能（删去相关siwtch也不行），请问如何修改meta istruction或者其他处理解锁模型plugin能力

**Comment by camphora** [comment]
已经解决，在训练语料中查询到了相关操作，可以咱超sft_data/conversations/conversations_with_plugins/text2_img/ 下文件的meta_instruction

**Comment by camphora** [comment]
已经解决，在训练语料中查询到了相关操作，可以咱超sft_data/conversations/conversations_with_plugins/text2_img/ 下文件的meta_instruction

**Comment by firdota** [comment]
您好，能分享一下怎么用的吗？
