### ISSUE TITLE
网页demo运行，链接打不开

### ISSUE THREAD

**Issue by guiniao** [OpenLMLab/MOSS#145]
在centos上部署好，运行moss_gui_demo.py，已经提示Running on local URL:  http://127.0.0.1:7860，但是网页打开，显示无法访问

**Comment by WeileiZeng** [comment]
你是在centos上本地打开 http://127.0.0.1:7860 吗

**Comment by genghaojie123** [comment]
> 在centos上部署好，运行moss_gui_demo.py，已经提示Running on local URL: [http://127.0.0.1:7860，但是网页打开，显示无法访问](http://127.0.0.1:7860%EF%BC%8C%E4%BD%86%E6%98%AF%E7%BD%91%E9%A1%B5%E6%89%93%E5%BC%80%EF%BC%8C%E6%98%BE%E7%A4%BA%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE)

修改脚本中启动的配置：demo.queue().launch(share=False, inbrowser=True,server_name="0.0.0.0",server_port=7860)，就可以从外部访问了。

**Comment by JovenChu** [comment]
我是在ubuntu18.04上用容器部署的，可参考：
1、卡在gradio的页面无法加载：需要降低gradio版本，以免高版本检查google字体

- pip install gradio==3.21.0

2、修改【/MOSS/moss_gui_demo.py】文件的最后一行

- demo.queue().launch(server_name='0.0.0.0', server_port=7860, share=False, inbrowser=True)
