### ISSUE TITLE
商业应用？

### ISSUE THREAD

**Issue by ghosthamlet** [OpenLMLab/MOSS#152]
README中说：“如需将本项目所含模型用于商业用途或公开部署，请签署[本文件](https://github.com/OpenLMLab/MOSS/blob/main/MOSS_agreement_form.pdf)并发送至[robot@fudan.edu.cn](mailto:robot@fudan.edu.cn)取得授权，商用情况仅用于记录，不会收取任何费用。”
即所有这些开源模型可以商用，但这些模型的指令数据是通过openai的GPT模型生成的，openai好像有条款说用它的模型生成的数据训练的新模型不能商用，如果我们商用MOSS模型，会不会有问题？

**Comment by txsun1997** [comment]
@ghosthamlet 商用在我们方面不存在问题，OpenAI是否存在隐患请自行评估

**Comment by ghosthamlet** [comment]
明白了，谢谢
