### ISSUE TITLE
想请教下，项目中给的微调示例，会更新模型的多少参数？对显存的要求是多少呢？

### ISSUE THREAD

**Issue by tjulh** [OpenLMLab/MOSS#160]
如题，希望有大佬能帮解答~

**Comment by txsun1997** [comment]
更新模型的全量参数，对显存的要求取决于你的训练配置，例如使用deepspeed zero-3 + checkpointing微调最大长度为1024的16B MOSS约需要8张80GB A100共640GB显存，若使用cpu/nvme offload可以更小显存

**Comment by ChawDoe** [comment]
> 更新模型的全量参数，对显存的要求取决于你的训练配置，例如使用deepspeed zero-3 + checkpointing微调最大长度为1024的16B MOSS约需要8张80GB A100共640GB显存训练一天一个epoch，若使用cpu/nvme offload可以更小显存

It's there any way to set the context length from 2048 to 1024 without re-processing the data?

**Comment by tjulh** [comment]
> 

谢谢大佬。另外这里指的是batchsize=1的情况吗

**Comment by tjulh** [comment]
> 更新模型的全量参数，对显存的要求取决于你的训练配置，例如使用deepspeed zero-3 + checkpointing微调最大长度为1024的16B MOSS约需要8张80GB A100共640GB显存训练一天一个epoch，若使用cpu/nvme offload可以更小显存

谢谢大佬。请问这里是指batchsize=1的情况吗
