### ISSUE TITLE
MOSS有没有官方技术交流群啊

### ISSUE THREAD

**Issue by ImGoodBai** [OpenLMLab/MOSS#162]
直接安装官方的流程安装还是有一些小问题，比如显存不够等等。如果有一个交流群可以方便大家快速沟通，解决问题。壮大MOSS用户群！

**Comment by TinQlo** [comment]
感觉没太大必要，issues里已经好多人填坑了

**Comment by ImGoodBai** [comment]
> 感觉没太大必要，issues里已经好多人填坑了

目前看起来效率不高

**Comment by txsun1997** [comment]
![image](https://user-images.githubusercontent.com/37499649/234473867-6783b1da-253b-4717-abc7-7575ebdba2ff.png)
@ImGoodBai @TinQlo

**Comment by h123c** [comment]
群满了，能拉进去吗

**Comment by zshmbbs** [comment]
群满了，求开门

**Comment by BeckShe** [comment]
工作完，才看到这个官方群消息。群满了，求开门

**Comment by lin-cop** [comment]
主页上有个微信群，可以直接加

**Comment by huqingjieClark** [comment]
2群也满了

**Comment by sheldonlll** [comment]
群满了emm

**Comment by dasepli** [comment]
新群二维码已更新，链接：https://github.com/OpenLMLab/MOSS/blob/main/examples/WeChatGroupQR.jpg

请关注主页README ’官方微信群‘ 部分。

**Comment by online2311** [comment]
二群已经也进不去了，求更新。
