### ISSUE TITLE
would you open source the code of pretraining? I wonder how to do tensor parallel. 

### ISSUE THREAD

**Issue by zixiliuUSC** [OpenLMLab/MOSS#163]
hi, openLML team, I'm quite curious about how to do tensor parallel in pretraining. Do you have plans to open source the code of pretraining? Or even just giving some examples about how to do tensor parallel or model sharding during pretraining would be appreciated.

**Comment by txsun1997** [comment]
hi @zixiliuUSC  we did not use tensor parallel. we adopted pipeline parallel and zero-1. We are considering open-source the pretraining code
