### ISSUE TITLE
finetune_moss.py#L121

### ISSUE THREAD

**Issue by BlackBearBiscuit** [OpenLMLab/MOSS#165]
https://github.com/OpenLMLab/MOSS/blob/96b34aec5e4cac6dd96778c8c5eac26d36947b38/finetune_moss.py#L121
Maybe you need to tweak the code?
batch_attn_mask = torch.nn.utils.rnn.pad_sequence(batch_input_ids, batch_first=True, padding_value=0).to(torch.bool)
-->batch_attn_mask = torch.nn.utils.rnn.pad_sequence(batch_attn_mask, batch_first=True, padding_value=0).to(torch.bool)

**Comment by xyltt** [comment]
Yeah, thanks!
