### ISSUE TITLE
总是提示文件缺失 index.json

### ISSUE THREAD

**Issue by youtehub** [OpenLMLab/MOSS#179]
错误如下:
ValueError: /home/mist/.cache/huggingface/hub/models--fnlp--moss-moon-003-sft-int4/snapshots/e3f0d7e7fba3944d5932ca2608b816678220ed25 is not a folder containing a `.index.json` file.
模型: models--fnlp--moss-moon-003-sft-int4，int8都有这个问题

**Comment by youtehub** [comment]
完全用官方的脚本跑的，总是缺失文件

**Comment by xiami2019** [comment]
量化模型目前只支持单卡加载，请使用Readme中的方法加载量化模型
model = AutoModelForCausalLM.from_pretrained("fnlp/moss-moon-003-sft-int4", trust_remote_code=True).half().cuda()
