### ISSUE TITLE
Running MOSS with multiple GPU with low GRAM（如何使用多张小显存GPU运行MOSS）

### ISSUE THREAD

**Issue by skywalkerIIII** [OpenLMLab/MOSS#182]
我们有单机8卡   Tesla T4（16GB），能否运行MOSS

**Comment by yhyu13** [comment]
moss 目前gptq并不支持模型分布，fp16版本32GB显存，2048 token满80GB显存左右，8卡可以运行的吧。题主可以试试

**Comment by skywalkerIIII** [comment]
> moss 目前gptq并不支持模型分布，fp16版本32GB显存，2048 token满80GB显存左右，8卡可以运行的吧。题主可以试试

实测4块tesla T4可以回答基本的问题，但是长度长的会hang死，现在准备加到5快卡试试

**Comment by skywalkerIIII** [comment]
测试5块T4（16GB）可以进行相对长一点的(200+）长度的回答（FP16）

**Comment by skywalkerIIII** [comment]
Running moss in multiple GPU with smaller GRAM is tested.
you can use at least 4 Tesla T4(5 recommended) to running this model(FP16)
