### ISSUE TITLE
执行量化版本模型moss-moon-003-sft-int4，如何指定本地模型和代码

### ISSUE THREAD

**Issue by yfq512** [OpenLMLab/MOSS#184]
每次运行代码时总会去执行缓存里的代码：“ /root/.cache/huggingface/modules/transformers_modules/……”，即便本地创建了 "fnlp/moss-moon-003-sft-int4/" 这个目录，最终也会执行缓存里的代码，导致每次执行到新的缓存都要去那修改代码才跑的通，有没有一劳永逸的方法，或者指定本地模型或代码的方法？

**Comment by sssssshf** [comment]
请问你是如何修改目录位置的，我下在int4这个模型放在项目目录 下，运行int给的示例代码会报错。请您看一下：
![image](https://user-images.githubusercontent.com/68574922/234740109-dede72d5-5c89-4b78-9f14-e959294322b6.png)
![image](https://user-images.githubusercontent.com/68574922/234740132-0cc6e643-c349-4f8f-8bcc-c37d625666ea.png)

**Comment by sssssshf** [comment]
> 每次运行代码时总会去执行缓存里的代码：“ /root/.cache/huggingface/modules/transformers_modules/……”，即便本地创建了 "fnlp/moss-moon-003-sft-int4/" 这个目录，最终也会执行缓存里的代码，导致每次执行到新的缓存都要去那修改代码才跑的通，有没有一劳永逸的方法，或者指定本地模型或代码的方法？

triton 这个依赖我已经安装过了

**Comment by yfq512** [comment]
> > 每次运行代码时总会去执行缓存里的代码：“ /root/.cache/huggingface/modules/transformers_modules/……”，即便本地创建了 "fnlp/moss-moon-003-sft-int4/" 这个目录，最终也会执行缓存里的代码，导致每次执行到新的缓存都要去那修改代码才跑的通，有没有一劳永逸的方法，或者指定本地模型或代码的方法？
> 
> triton 这个依赖我已经安装过了

指定本地模型这个我也没有跑通，看你这个错误就是路径问题，autotune这个方法没导进来

**Comment by sssssshf** [comment]
> > > 每次运行代码时总会去执行缓存里的代码：“ /root/.cache/huggingface/modules/transformers_modules/……”，即便本地创建了 "fnlp/moss-moon-003-sft-int4/" 这个目录，最终也会执行缓存里的代码，导致每次执行到新的缓存都要去那修改代码才跑的通，有没有一劳永逸的方法，或者指定本地模型或代码的方法？
> > 
> > 
> > triton 这个依赖我已经安装过了
> 
> 指定本地模型这个我也没有跑通，看你这个错误就是路径问题，autotune这个方法没导进来

你不会报这个错是吗，我这个错误怎么导致的我要怎么修改呢

**Comment by yfq512** [comment]
解决了，原来缓存的代码都是从本地拷贝过去的，修改本地代码就可以啦😂

**Comment by sssssshf** [comment]
> 解决了，原来缓存的代码都是从本地拷贝过去的，修改本地代码就可以啦joy

可否加个联系方式 教一下我

**Comment by yfq512** [comment]
> 

wx发来，我加你

**Comment by sssssshf** [comment]
> > 
> 
> wx发来，我加你

15736267362
