### ISSUE TITLE
社区群

### ISSUE THREAD

**Issue by IanZ2020** [OpenLMLab/MOSS#19]
请问能创建一个社区群方便讨论技术问题嘛？

**Comment by YYGe01** [comment]
我刚创建了个Moss微信群，有意向复现的可以加群防踩坑。

![微信图片_20230421201111_288x405](https://user-images.githubusercontent.com/45594167/233633220-73e06072-ae6f-40e3-a11c-53b4e4ffa78d.jpg)

**Comment by txsun1997** [comment]
![image](https://user-images.githubusercontent.com/37499649/234478494-9cca9025-61c2-45c0-8c97-417c32bfef68.png)
官方交流群见上
