### ISSUE TITLE
请问本地部署最低配置是什么

### ISSUE THREAD

**Issue by casjyhq** [OpenLMLab/MOSS#2]
请问本地部署最低配置是什么

**Comment by casjyhq** [comment]
介绍中最低要求是3090，T.T

**Comment by ninerui** [comment]
现在开放的是fp16模型， 是需要30g显存，之后会开放量化的

**Comment by 2132660698** [comment]
目前跑起来需要的显存，给大家参考。
![image](https://user-images.githubusercontent.com/94035926/233560507-01f1ea30-bd4a-4684-9ca6-fe716b20252f.png)

**Comment by milk-bottle-liyu** [comment]
我用的4张titan xp，就是比较慢。。。

**Comment by YYGe01** [comment]
> 目前跑起来需要的显存，给大家参考。 

兄弟，我有两张40G的 A100，能跑起来嘛

**Comment by casjyhq** [comment]
啊 这配置要求真高啊

**Comment by lwh9346** [comment]
我用的是单张4080
#35

**Comment by txsun1997** [comment]
@casjyhq @YYGe01 各精度模型推理所需显存已经更新到README
