### ISSUE TITLE
微信群超过200人，只可通过群成员邀请进群！！！

### ISSUE THREAD

**Issue by filesos** [OpenLMLab/MOSS#200]
官方提供的交流群200人满了，微信群超过200人，只可通过群成员邀请进群。。。

**Comment by sheldonlll** [comment]
人员满了，佬再开一个群qaq

**Comment by insist93** [comment]
+1

**Comment by leiwhere** [comment]
+1

**Comment by youtehub** [comment]
要不找个人来个2000人的大群，然后转给官方人员管理

**Comment by Gusicun** [comment]
官方交流群咋加啊大佬们，有新群吗

**Comment by dasepli** [comment]
![WeChatGroupQR](https://github.com/OpenLMLab/MOSS/blob/main/examples/WeChatGroupQR.jpg)
新群二维码已更新；

**Comment by dasepli** [comment]
新群二维码已更新，链接：https://github.com/OpenLMLab/MOSS/blob/main/examples/WeChatGroupQR.jpg

**Comment by Cocoalate** [comment]
> 新群二维码已更新，链接：https://github.com/OpenLMLab/MOSS/blob/main/examples/WeChatGroupQR.jpg

又过期了，能再拉一下嘛
