### ISSUE TITLE
数据怎么能看到原文？多谢多谢！

### ISSUE THREAD

**Issue by guotong1988** [OpenLMLab/MOSS#208]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/4702353/235093204-b453892f-0b8d-4da5-9d13-b3659dcf3246.png">

https://huggingface.co/datasets/fnlp/moss-002-sft-data/tree/main

**Comment by dasepli** [comment]
这个应该是中文编码的问题，可以试试eval(string)一下，另外使用json load数据的时候应该会自动转成中文。

**Comment by AllenWGX** [comment]
@dasepli +1。直接json.load就可以了。
![yd-github](https://user-images.githubusercontent.com/23058056/236123626-98ffcf37-2c78-451c-84a1-dcc6b429db8d.png)

**Comment by gg22mm** [comment]
感觉与 moss-003-sft-data  和 moss-003-sft-plugin-data 样式的数据变化好大呀，不能使用同一种样式的吗
