### ISSUE TITLE
提供一个ModelWhale平台在线部署moss-moon-003-sft、进行模型推理的demo项目

### ISSUE THREAD

**Issue by jsl9208** [OpenLMLab/MOSS#22]
项目链接 https://www.heywhale.com/mw/project/6442706013013653552b7545

@xiami2019 @txsun1997 能否考虑加进readme作为部署方式的补充？

**Comment by xiami2019** [comment]
感谢支持！可以拉一个PR~

**Comment by jsl9208** [comment]
> Hi @jsl9208 感谢支持～ 已经添加到readme。另外刚刚修复了一些使用模型推理的bug，请根据最新的inference代码更新您平台的MOSS相关代码

没问题，感谢添加~
