### ISSUE TITLE
使用streamlit运行模型推理报错，请教解决方案～

### ISSUE THREAD

**Issue by zlht812** [OpenLMLab/MOSS#220]
运行命令：
streamlit run moss_web_demo_streamlit.py --server.port 8888 -- --model_name E:\model\Moss\003-sft-int4 --gpu 0 
报错如下：
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 301989888 bytes.

机器配置：
内存 64G，可用40+G
显卡 3080ti  12G显存 
win10系统

请求支持，🙏

**Comment by ArlanCooper** [comment]
这个不是很显然了吗？显存不够
