### ISSUE TITLE
能否提供一个简单的UI工具来启动模型？

### ISSUE THREAD

**Issue by etali** [OpenLMLab/MOSS#24]
能否提供一个简单的UI工具来启动模型？

**Comment by txsun1997** [comment]
hi @etali 如果最近有时间我们会提供一个streamlit实现的web UI

**Comment by 00INDEX** [comment]
Hi @etali 我们已经加入了由 [Pull Request](https://github.com/OpenLMLab/MOSS/pull/25) 提供的 GUI 工具，您可以通过 [moss_gui_demo.py](https://github.com/OpenLMLab/MOSS/blob/main/moss_gui_demo.py) 来启用此工具。
