### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by sk142857** [OpenLMLab/MOSS#257]
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

![image](https://github.com/OpenLMLab/MOSS/assets/75599950/8f1affeb-3f4b-44e1-9804-cf751a6de843)

**Comment by k55k32** [comment]
运行参数的 `num_processes` 改一下， 你有多个块GPU，就填多少

**Comment by Yiwen-Yang-666** [comment]
我改完num_processes 还会出现这个错误，什么原因呢 @k55k32 @sk142857
