### ISSUE TITLE
这个训练数据格式到底是什么样的？

### ISSUE THREAD

**Issue by sk142857** [OpenLMLab/MOSS#260]
把所有的数据放到 train.jsonl 之后，也是报错。感觉乱七八糟的！

![image](https://github.com/OpenLMLab/MOSS/assets/75599950/f799ece9-abe5-4baa-b42f-5bc2263d5d1d)

**Comment by WenjingBao** [comment]
您好，想请问一下您解决了这个问题了吗？
如果是的话，烦请告知如何解决的，感激不尽
