### ISSUE TITLE
moss如何转onnx呢？

### ISSUE THREAD

**Issue by JIEKEXIAN** [OpenLMLab/MOSS#283]
我试过把moss转onnx来提速，但是发现转成onnx之后速度反而变慢了，不知道大家有没有转成onnx并成功提速的呢？都是在GPU上对比的。

**Comment by yanguowei316** [comment]
> 

请问您是如何转为onnx格式的 ？

**Comment by JIEKEXIAN** [comment]
> 

就是用的torch.onnx.export()这个接口，指定好输入和输出就可以。

**Comment by yanguowei316** [comment]
> > 
> 
> 就是用的torch.onnx.export()这个接口，指定好输入和输出就可以。

N您可以分享一下代码吗？我在转换的时候一个劲的遇到错误，

**Comment by JIEKEXIAN** [comment]
> > > 
> > 
> > 
> > 就是用的torch.onnx.export()这个接口，指定好输入和输出就可以。
> 
> N您可以分享一下代码吗？我在转换的时候一个劲的遇到错误，

**Comment by JIEKEXIAN** [comment]
> > > 
> > 
> > 
> > 就是用的torch.onnx.export()这个接口，指定好输入和输出就可以。
> 
> N您可以分享一下代码吗？我在转换的时候一个劲的遇到错误，

我用的fastgpt转的，可以参考下这个：https://zhuanlan.zhihu.com/p/533629034，不过源码你要改下。

**Comment by ChuYy-712** [comment]
> > > > 
> > > 
> > > 
> > > 就是用的torch.onnx.export()这个接口，指定好输入和输出就可以。
> > 
> > 
> > N您可以分享一下代码吗？我在转换的时候一个劲的遇到错误，
> 
> 我用的fastgpt转的，可以参考下这个：[https://zhuanlan.zhihu.com/p/533629034，不过源码你要改下。](https://zhuanlan.zhihu.com/p/533629034%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%BA%90%E7%A0%81%E4%BD%A0%E8%A6%81%E6%94%B9%E4%B8%8B%E3%80%82)

请问你转的是哪个模型呢
