### ISSUE TITLE
微调如何指定GPU

### ISSUE THREAD

**Issue by lukaswangbk** [OpenLMLab/MOSS#286]
测试微调的时候发现GPU永远会用第一张卡，请问要怎么指定用那几张卡呢？
目前尝试了在run.sh中加入CUDA_VISIBLE_DEVICES=1，但是还是第0张卡，在fine_tuning.py中指定os也是不行
以下是我的命令：
num_machines=1
num_processes=1
machine_rank=0
CUDA_VISIBLE_DEVICES=3
accelerate launch \
	--config_file ./configs/sft.yaml \
	--num_processes $num_processes \
	--num_machines $num_machines \
	--machine_rank $machine_rank \
	--deepspeed_multinode_launcher standard finetune_moss.py \
	--model_name_or_path fnlp/moss-moon-003-base \
	--data_dir ./sft_data \
	--output_dir ./ckpts/moss-moon-003-sft \
	--log_dir ./train_logs/moss-moon-003-sft \
	--n_epochs 2 \
	--train_bsz_per_gpu 1 \
	--eval_bsz_per_gpu 1 \
	--learning_rate 0.000015 \
	--eval_step 200 \
	--save_step 2000

**Comment by 631068264** [comment]
@lukaswangbk 大佬解决了吗 求救

**Comment by lukaswangbk** [comment]
> 

需要在文件最上面import os然后更改CUDA_VISIBLE_DEVICES（理论上是要在import torch之前）

**Comment by 631068264** [comment]
@lukaswangbk 
<img width="1004" alt="image" src="https://github.com/OpenLMLab/MOSS/assets/8144089/1d9ff8a6-00b8-4457-aa98-5bf1fcaa00db">

<img width="975" alt="image" src="https://github.com/OpenLMLab/MOSS/assets/8144089/13a082f7-c52a-4a9c-817a-5be38572b184">
不可以。。。

**Comment by graphnj** [comment]
CUDA_VISIBLE_DEVICES=3前面加export  
或将
CUDA_VISIBLE_DEVICES=3与accelerate launch放一行  `CUDA_VISIBLE_DEVICES=3 accelerate launch`
试下
