### ISSUE TITLE
请问中文表现和chatglm6b相比哪个好

### ISSUE THREAD

**Issue by rayvzn119** [OpenLMLab/MOSS#3]
目前感觉中文开源大模型效果最好的就是chatglm6b，大佬有内部测试过吗？

**Comment by ScottishFold007** [comment]
> 目前感觉中文开源大模型效果最好的就是chatglm6b，大佬有内部测试过吗？

你是来砸场子的么？

**Comment by Siegfried-qgf** [comment]
我怀疑你在搞事情

**Comment by upupc** [comment]
(⊙_⊙)

**Comment by zzcgithub** [comment]
哪位大佬用gpt4给来个测评

**Comment by terrifyzhao** [comment]
理论上来说16B的模型效果肯定比6B的好

**Comment by Aida-yy** [comment]
实际上的效果6b大于16B

**Comment by YYGe01** [comment]
> 

能细细说下吗

**Comment by MrToy** [comment]
亲测，ChatGLM-6B强一些

**Comment by Ricardokevins** [comment]
确实对效果挺好奇的。。。评测应该很快就有人做了

**Comment by rayvzn119** [comment]
实测了一下，和chatglm6b效果有不少差距，例如在做prompt tuning时，moss经常会无法准确理解用户的意图，导致回答很奇怪。不过考虑到moss基座只有16b，glm的基座是130b，语义理解能力有差距很正常。感谢moss团队的开源，期待后续尝试更大的基座，看能否有进一步提高

**Comment by rayvzn119** [comment]
> 理论上来说16B的模型效果肯定比6B的好

不是参数量越大越好的，moss16b实测效果不如glm6b，感觉跟基座模型能力有关

**Comment by CodePothunter** [comment]
> 实测了一下，和chatglm6b效果有不少差距，例如在做prompt tuning时，moss经常会无法准确理解用户的意图，导致回答很奇怪。不过考虑到moss基座只有16b，glm的基座是130b，语义理解能力有差距很正常。感谢moss团队的开源，期待后续尝试更大的基座，看能否有进一步提高

chatglm 6B的基座就是6B

**Comment by ykk648** [comment]
我看来看去，哪里写了16B？

**Comment by Ricardokevins** [comment]
> 我看来看去，哪里写了16B？

看不懂readme的中文啊

**Comment by rayvzn119** [comment]
> > 实测了一下，和chatglm6b效果有不少差距，例如在做prompt tuning时，moss经常会无法准确理解用户的意图，导致回答很奇怪。不过考虑到moss基座只有16b，glm的基座是130b，语义理解能力有差距很正常。感谢moss团队的开源，期待后续尝试更大的基座，看能否有进一步提高
> 
> chatglm 6B的基座就是6B

glm有个130b的基座，6b是基于这个优化训练而来的

**Comment by CodePothunter** [comment]
> > > 实测了一下，和chatglm6b效果有不少差距，例如在做prompt tuning时，moss经常会无法准确理解用户的意图，导致回答很奇怪。不过考虑到moss基座只有16b，glm的基座是130b，语义理解能力有差距很正常。感谢moss团队的开源，期待后续尝试更大的基座，看能否有进一步提高
> > 
> > 
> > chatglm 6B的基座就是6B
> 
> glm有个130b的基座，6b是基于这个优化训练而来的

“基于”其实基于数据和经验，并非基于130B的模型（6B不是130B蒸馏得到的），所以从模型规模来说，这就是6B。

**Comment by ykk648** [comment]
> > 我看来看去，哪里写了16B？
> 
> 看不懂readme的中文啊

这个README我是看不懂，一堆没用的中文，ctrl+F 16b 在哪呢？

**Comment by rayvzn119** [comment]
> > > 我看来看去，哪里写了16B？
> > 
> > 
> > 看不懂readme的中文啊
> 
> 这个README我是看不懂，一堆没用的中文，ctrl+F 16b 在哪呢？

16b就是160亿的意思，moss介绍里说了，它的参数量是160亿

**Comment by txsun1997** [comment]
@MrToy @rayvzn119 @ykk648 @CodePothunter @YYGe01 @Aida-yy @ScottishFold007 @Siegfried-qgf @upupc @iron-js 
之前README中给出的repetition penalty会导致代码生成质量低下，参考https://github.com/OpenLMLab/MOSS/issues/42
