### ISSUE TITLE
P40使用moss-moon-003-sft-int4/量化模型推理报错

### ISSUE THREAD

**Issue by dubaoquan404** [OpenLMLab/MOSS#302]
python3: /project/lib/Analysis/Utility.cpp:136: bool mlir::supportMMA(mlir::Value, int): Assertion `(version == 1 || version == 2) && "Unexpected MMA layout version found"' failed.

**Comment by 13875892872** [comment]
我也是同样的错误，P40 int4量化推理报错。

**Comment by boystray** [comment]
Pascal架构的显卡不支持，硬件问题。
[](https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/142)

**Comment by boystray** [comment]
> Pascal架构的显卡不支持，硬件问题。

https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/142

**Comment by boystray** [comment]
试试这个方案
https://github.com/openai/triton/issues/1271
