### ISSUE TITLE
MOSS next release?

### ISSUE THREAD

**Issue by yhyu13** [OpenLMLab/MOSS#371]
Hi,

Would there be any update since early September? Would there be next base model MOss 2.0?

**Comment by yhyu13** [comment]
dead?

**Comment by lhtpluto** [comment]
> Hi,
> 
> Would there be any update since early September? Would there be next base model MOss 2.0?

MOSS的作者还是个学生，没有足够的精力去演进MOSS V2.0

就目前来看，此项目处于冬眠状态

**Comment by yhyu13** [comment]
Sure thing!
