### ISSUE TITLE
请问moss_api的本地化服务是如何启动的？

### ISSUE THREAD

**Issue by isLinXu** [OpenLMLab/MOSS#4]
有注意到repo目录下的moss-api的pdf文件，大致浏览了一下是类似于web接口的服务，
想请问该服务的启动或打开方式是如何实现和使用的，直接基于推理和参数去改写嘛，
关于这部分相关的内容，希望可以在readme中补充，在该issue做个简单的答复亦可，
最后，respect moss的工作👍

**Comment by piglaker** [comment]
需要自己部署一下，大概就是allocate gpu load model之后监听端口，preprocess batching inference postprocess 然后返回结果

**Comment by 2132660698** [comment]
期待官方搞一下，特别是moss-moon-003-sft-plugin的API

**Comment by txsun1997** [comment]
@isLinXu @2132660698 由于服务器资源有限，暂时仅面向企业开放API服务
