### ISSUE TITLE
[QUESTION] vocab.txt

### ISSUE THREAD

**Issue by DongqiShen** [OpenLMLab/MOSS#41]
1. 用什么编码打开呢？
2. 为什么会有很多 数字 字符串的编码？

**Comment by xyltt** [comment]
因为词表是BBPE算法训练得到的，所以中文是以byte形式显示的，并不是出现了乱码。

**Comment by DongqiShen** [comment]
@xyltt 谢谢解答。那我的理解是，一个汉字由3个byte表示，而在BBPE的训练中是会把一个汉字切分开的，所以一个token可能有4个bytes，所以无法用正常显示？

**Comment by xyltt** [comment]
是的

**Comment by DongqiShen** [comment]
Big Thanks. Closed!
