### ISSUE TITLE
int4量化版本运行报错 

### ISSUE THREAD

**Issue by icuai** [OpenLMLab/MOSS#45]
环境： 
RTX 4090
WSL2, Ubuntu 22
torch version: 2.0.0+cu117

```
RuntimeError: Expected all tensors to be on the same device, but found at least two 
devices, cuda:0 and cpu! (when checking argument for argument index in method 
wrapper_CUDA__index_select)
```

![image](https://user-images.githubusercontent.com/10334422/233788692-ba8e3663-490a-4fc4-98fc-f30fdeb46645.png)

**Comment by Tongjilibo** [comment]
你这个错误比较好解决吧，因为米的model放在gpu上，但是inputs还在cpu上，试试下面这么修改是否可以
`inputs = tokenizer(plain_text, return_tensors='pt').cuda()`

**Comment by txsun1997** [comment]
@icuai readme有点bug，稍后更新

**Comment by Hzfinfdu** [comment]
已修复

**Comment by icuai** [comment]
感谢，已经可以正常运行了

**Comment by icuai** [comment]
感谢，已经可以正常运行了
