### ISSUE TITLE
参考chatglm的int8来低成本部署moss

### ISSUE THREAD

**Issue by Tongjilibo** [OpenLMLab/MOSS#47]
参考chatglm-6b的[moss的int8量化部署](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_moss.py)，单卡最低占用约18个G，此外也有转chatglm-6b、bella、llama-7b的推理(含量化版本，单卡12G可跑)及微调，见[bert4torch](https://github.com/Tongjilibo/bert4torch/blob/master/examples/llm/README.md)

**Comment by txsun1997** [comment]
@Tongjilibo 今天会支持moss-moon-sft和moss-moon-sft-plugin的4bit 8bit版本

**Comment by dasepli** [comment]
已支持，请check README开源清单：https://github.com/OpenLMLab/MOSS#%E6%A8%A1%E5%9E%8B
