### ISSUE TITLE
申请API

### ISSUE THREAD

**Issue by pronoobe** [OpenLMLab/MOSS#48]
谢谢

**Comment by txsun1997** [comment]
https://github.com/OpenLMLab/MOSS/issues/14

**Comment by pronoobe** [comment]
??7傔?D3衭{*俘俔@***@***.***|!x??о瞂ftwn&?鼑  箱襒眘)喵  d?輑田璐Vm系y1太莭W棆鲾窓眙霿рd??e菄躞 tXF;驌
