### ISSUE TITLE
plugin模型，有用python代码写的使用例子吗？而非只是动态图片

### ISSUE THREAD

**Issue by hanswang73** [OpenLMLab/MOSS#51]
plugin模型，有用python代码写的使用例子吗？而非只是动态图片

**Comment by piglaker** [comment]
您好 ，plugin生效需要moss 后端，moss推理和tools server一起工作完成。moss前后端：
前端：https://github.com/singularity-s0/openchat_frontend
后端：https://github.com/JingYiJun/MOSS_backend
推理部署：https://github.com/OpenLMLab/MOSS_Vortex
websearch tool server：
https://github.com/OpenLMLab/MOSS_WebSearchTool

**Comment by fengtianyu88** [comment]
> 您好 ，plugin生效需要moss 后端，moss推理和tools server一起工作完成。moss前后端： 前端：https://github.com/singularity-s0/openchat_frontend 后端：https://github.com/JingYiJun/MOSS_backend 推理部署：https://github.com/OpenLMLab/MOSS_Vortex websearch tool server： https://github.com/OpenLMLab/MOSS_WebSearchTool

希望有一个简单的本地部署说明~

**Comment by piglaker** [comment]
已更新

**Comment by AHNU** [comment]
这么复杂么，尝试部署感觉比较复杂呢，可以再完善下相关文档么。另外各个依赖直接提供docker image最好，不用用户自己从头打镜像了。

**Comment by AHNU** [comment]
目前只看到一个镜像，具体说明文档辛苦发下，感性～

**Comment by firdota** [comment]
想尝试一下插件功能，请问会出相关说明文档吗？

**Comment by txsun1997** [comment]
@hanswang73 @AHNU @firdota 插件版MOSS的使用说明已经更新到README

**Comment by firdota** [comment]
感谢！
