### ISSUE TITLE
meta_instruction问题

### ISSUE THREAD

**Issue by JaheimLee** [OpenLMLab/MOSS#59]
如果说调用plugin插件需要额外的prompt信息是可以理解的。但是普通对话为什么要引入meta_instruction？即便想靠prompt引导模型输出正向结果，这个encode之后长度有200多是不是太浪费了？

**Comment by yangs16** [comment]
去掉meta instruction试试看，没准对效果影响不大

**Comment by dasepli** [comment]
Q1：因为带plugin的数据和不带plugin的数据是一块SFT的，为了保持数据格式的一致性，我们在普通对话里也引入了meta_instruction；
Q2：感谢对meta instruction的长度的建议，我们在下一次版本中会考虑优化这一部分；
