### ISSUE TITLE
请问MOSS网页版本何时再次开放？

### ISSUE THREAD

**Issue by SchweitzerGAO** [OpenLMLab/MOSS#6]
如题

**Comment by StevenH7-S** [comment]
同问

**Comment by flybirdz** [comment]
已经开放了，直接填写问卷申请内测 然后收到邀请码后注册登录体验 网址还是原来那个 没保存的话上网搜搜

**Comment by SchweitzerGAO** [comment]
好的，谢谢

> 已经开放了，直接填写问卷申请内测 然后收到邀请码后注册登录体验 网址还是原来那个 没保存的话上网搜搜
