### ISSUE TITLE
请问可以多卡推理吗，目前单卡显存很小，跑不起来

### ISSUE THREAD

**Issue by uloveqian2021** [OpenLMLab/MOSS#7]

**Comment by 00INDEX** [comment]
通过`transformers`的自动模型切分功能可以很方便地实现多卡推理，您可以参考 [moss_cli_demo.py](https://github.com/OpenLMLab/MOSS/blob/c8efd88310479c2a9c8070d84c6e1af529833f91/moss_cli_demo.py#L24) 中的第 24 至第 29 行以获得更多帮助。

**Comment by jacklanda** [comment]
> 通过`transformers`的自动模型切分功能可以很方便地实现多卡推理，您可以参考 [moss_cli_demo.py](https://github.com/OpenLMLab/MOSS/blob/c8efd88310479c2a9c8070d84c6e1af529833f91/moss_cli_demo.py#L24) 中的第 24 至第 29 行以获得更多帮助。

可以多卡 sft 么？目前试了下，似乎基于 accelerate 的 `device_map` 做 pipeline 并行的方法会造成 input 跟 下一个 block 的 layernorm 发生 different device 的错误。这个如何解决呢？谢谢~
