### ISSUE TITLE
V100-32G运行提示缺400M显存（非量化版本）

### ISSUE THREAD

**Issue by cnsky2016** [OpenLMLab/MOSS#79]
RuntimeError: CUDA out of memory. Tried to allocate 1.22 GiB (GPU 0; 31.75 GiB total capacity; 29.57 GiB already allocated; 803.75 MiB free; 29.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Cocoalate** [comment]
碰到同样的问题，请问解决了么
