### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by kangxinghua** [OpenLMLab/MOSS#81]
![image](https://user-images.githubusercontent.com/2741535/233829083-ab8ef6e5-f076-4724-b701-383239361a1e.png)
报以上错误，但是我在我自己的环境CUDA是可以用的，如图：
![image](https://user-images.githubusercontent.com/2741535/233829169-9dfc8eb2-a027-4c5d-a6bb-37ca254f5c3d.png)
但是在moss环境是不可以用，如图：
![image](https://user-images.githubusercontent.com/2741535/233829211-59341271-6de1-4960-91ca-7a3b09087557.png)

**Comment by cnsky2016** [comment]
在moss环境下重新安装下torch，截图显示版本是1.10.1+cpu

**Comment by kangxinghua** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
重新安装torch，解决了。谢谢。
