### ISSUE TITLE
生成的回复有一些乱码英文

### ISSUE THREAD

**Issue by Leawnn** [OpenLMLab/MOSS#82]
![image](https://user-images.githubusercontent.com/56593035/233829286-1cab3408-4803-4377-8437-5090305e7da8.png)
![image](https://user-images.githubusercontent.com/56593035/233829229-13c4dbc6-969c-4475-9c36-dc31cece7cb6.png)
![image](https://user-images.githubusercontent.com/56593035/233829246-2bde47e8-1f45-4d4f-9fa7-0a143abe88dc.png)

**Comment by piglaker** [comment]
可能由于采样策略导致的生成错误
