### ISSUE TITLE
fnlp/moss-moon-003-sft 对话测试反馈

### ISSUE THREAD

**Issue by Coldmooon** [OpenLMLab/MOSS#94]
用 fnlp/moss-moon-003-sft 做了 2 组样例做了下测试，答案距离实用还有较大距离。

moss-moon-003-sft 的输出：
![1](https://user-images.githubusercontent.com/4266166/233845678-467e7bc3-eb55-46b9-9681-1ce98b0d5437.png)

ChatGLM-6B:
![2](https://user-images.githubusercontent.com/4266166/233845712-765355fc-092d-43f7-bb0d-2624df83665a.png)

ChatGPT3.5:
![3](https://user-images.githubusercontent.com/4266166/233845744-b81303eb-4436-4d76-819d-193bd432d6d3.png)

**Comment by SailNow** [comment]
模型容量差了十倍，还算是正常的吧，而且moss的训练语料感觉英文的占比还是太大了，chatGLM的训练预料大部分是中文，参数量虽然只有6b，但是表现的还是可以的
