### ISSUE TITLE
api问题

### ISSUE THREAD

**Issue by samoy1ed** [OpenLMLab/MOSS#98]
尊敬的团队：

您好！我是一名开发者，希望申请使用贵团队的API，Moss。

我计划使用Moss API 进行轻量级的模型使用。希望尝试作为第一个demo，我的demo主要是用于进行简单问答的功能。我相信Moss API可以提供给我需要的服务，并且可以极大地提高我的demo的质量。

我将会遵守您的API使用规范，并且尽可能减少对您系统的负载。我的联系方式为（2898985691@qq.com），如果您有任何问题或需要更多的信息，请不要犹豫地与我联系。

非常感谢您花时间阅读我的申请。我期待着您的回复，并希望能够在不久的将来开始使用Moss API。

        此致，
敬礼！

**Comment by exaggerated-dream** [comment]
哈哈哈.....ChatGPT生成的吧............

**Comment by Ingnaryk** [comment]
> 哈哈哈.....ChatGPT生成的吧............

你这么一说还真很像，我说怎么issue也要写信了。恕我直言应该是套皮盈利者写的

**Comment by txsun1997** [comment]
https://github.com/OpenLMLab/MOSS/issues/14
